# Generated by Django 2.2.4 on 2020-10-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('overview', models.CharField(blank=True, max_length=250)),
                ('release_date', models.DateField()),
                ('poster_url', models.CharField(max_length=100)),
                ('backdrop_url', models.CharField(max_length=100)),
                ('imdb_id', models.CharField(max_length=10)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Genre')),
            ],
        ),
    ]
