# Generated by Django 2.2.4 on 2020-11-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovieuser',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovieuser',
            name='photo_path',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
