# Generated by Django 2.2.4 on 2020-11-02 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201102_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moovieuser',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
