# Generated by Django 2.2.4 on 2020-11-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20201102_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(blank=True, to='lists.Movie'),
        ),
    ]
