# Generated by Django 2.2.4 on 2020-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20201029_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(to='lists.Movie')),
            ],
        ),
    ]
