# Generated by Django 2.2.4 on 2020-10-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20201029_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='movies',
        ),
        migrations.AddField(
            model_name='video',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='lists.Movie'),
        ),
    ]
